"""empty message

Revision ID: 68010b5d56c6
Revises: dd5dfa9a48da
Create Date: 2021-12-15 07:45:18.505026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68010b5d56c6'
down_revision = 'dd5dfa9a48da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('employee', sa.Column('date_employed', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'address')
    op.drop_column('employee', 'salary')
    op.drop_column('employee', 'date_employed')
    op.drop_column('employee', 'dob')
    # ### end Alembic commands ###
