"""empty message

Revision ID: 8d019d9df5e0
Revises: 68010b5d56c6
Create Date: 2021-12-16 08:05:16.489337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d019d9df5e0'
down_revision = '68010b5d56c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###
