"""initial migration

Revision ID: 8fbe0c29970a
Revises: 
Create Date: 2021-12-14 21:56:45.379162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbe0c29970a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('phone', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'employee', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'phone')
    # ### end Alembic commands ###
